{% set name = "dataclasses-json" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c287594d9fcea72dc42d6d3836cf14848c2dc5ce88f65ed61b36b57f515fe26

build:
  number: 0
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - pip
    - poetry-core >=1.2.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python
    - marshmallow >=3.18.0,<4.0.0
    - typing_inspect >=0.4.0,<1

test:
  imports:
    - dataclasses_json
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/lidatong/dataclasses-json
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easily serialize dataclasses to and from JSON
  description: |
    This library provides a simple API for encoding and decoding dataclasses to and from JSON.
    It is recursive, and supports arbitrary collections, datetime, UUID, and decimal objects.
  doc_url: https://lidatong.github.io/dataclasses-json/
  dev_url: https://github.com/lidatong/dataclasses-json

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - mxr-conda
